// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.Balances.Postgres;

namespace Service.Balances.Postgres.Migrations
{
    [DbContext(typeof(BalancesContext))]
    [Migration("20210219122232_ver_0")]
    partial class ver_0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("balances")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Service.Balances.Postgres.BalanceEntity", b =>
                {
                    b.Property<string>("WalletId")
                        .HasColumnType("text");

                    b.Property<string>("AssetId")
                        .HasColumnType("text");

                    b.Property<double>("Balance")
                        .HasPrecision(20)
                        .HasColumnType("double precision");

                    b.Property<string>("BrokerId")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Reserve")
                        .HasPrecision(20)
                        .HasColumnType("double precision");

                    b.Property<long>("SequenceId")
                        .HasColumnType("bigint");

                    b.HasKey("WalletId", "AssetId")
                        .HasName("PK_balances_balances");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("IX_balances_balances_wallet");

                    b.HasIndex("BrokerId", "ClientId")
                        .HasDatabaseName("IX_balances_balances_broker_client");

                    b.ToTable("balances");
                });
#pragma warning restore 612, 618
        }
    }
}
